
POST http://localhost:8080/classrooms
Content-Type: application/json


{
    "classname": "Math JC",
    "capacity" : 15
}

### GET classrooms
GET http://localhost:8080/classrooms
Content-Type: application/json

### GET classroom
GET http://localhost:8080/classrooms/3
Content-Type: application/json
###
PUT http://localhost:8080/classrooms/3
Content-Type: application/json
Authorization: Basic admin goodpassword

{
  "classname": "Johnny lesson",
  "capacity": 100
}

###
DELETE http://localhost:8080/classrooms/2

